package TP.Noyau;


public enum CategorieQRLEnfant {
    STRUCTURE_FAMILIALE,
    DYNAMIQUE_FAMILIALE,
    ANTECEDENTS_FAMILIAUX,
    CONDITIONS_NATALES,
    DEVELOPPEMENT_PSYCHOMOTEUR,
    DEVELOPPEMENT_LANGAGIER,
    CARACTERE_ET_COMPORTEMENT
}
